[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Enable optimizer and via-IR to fix stack too deep issues
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# CI profile (used by GitHub Actions)
[profile.ci]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
